### ISSUE TITLE
Show total raised in the fundraising section

### ISSUE THREAD

**Issue by corndogit** [SwanseaCompSci/tree-society-website#12]
Instead of the "and many more to come!" text in the last green circle, include a total amount raised 

Example:
![desktop view](https://corndog.s-ul.eu/62lSWghr.png)
![mobile view](https://corndog.s-ul.eu/VG0W6ku1.png)

The following fundraising event should also be added on:
Group in Zambia as part of **Swansea University Discovery** (volunteering) : £663.75
"[Money was] raised for a community group that we volunteered with when the Swansea University Discovery team ran a 4 week trip to Zambia in 2019."

**Comment by svejnohatomas** [comment]
The new total is £4336.70

**Comment by corndogit** [comment]
With Zambia trip added on, the new total is £5000.45
