### ISSUE TITLE
Remove numbering and right alignment of helping section in mobile view

### ISSUE THREAD

**Issue by corndogit** [SwanseaCompSci/tree-society-website#15]
Currently, when the helping section section collapses down to 1 element per row in mobile view, the second item text is still aligned to the right. It would be better to add a CSS breakpoint so that when the viewport width is low enough to make the elements collapse, the second element goes back to being left aligned.

This will take some rewriting of the HTML template file and additional CSS. This is because currently, the second element is aligned using the `text-right` Bootstrap class when the site is generated, which adds the line `text-align: right !important;` to the CSS for this div. A solution could be to use an [n-th child selector](https://css-tricks.com/almanac/selectors/n/nth-child/) in the parent div to target the second item in the helping section. This would also be better practice as the section could theoretically hold more than 3 items.

**Comment by svejnohatomas** [comment]
You can use the Bootstrap classes to get different alignments for different breakpoint. https://getbootstrap.com/docs/4.3/utilities/text/#text-alignment

There is going to be a similar Boostrap solution to get the images to the centre too
